# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.1.1.dev6+gb2ac51c.d20240607'
__version_tuple__ = version_tuple = (1, 1, 1, 'dev6', 'gb2ac51c.d20240607')
